services:
  celery_worker:
    command: >-
      uv run celery -A open_feed_reader worker -B -l INFO
    depends_on:
      - redis
    environment:
      - CELERY_BROKER=redis://redis:6379/0
    image: open-feed-reader:dev
    volumes:
      - db-data:/app/sqlite
      - media_files:/app/mediafiles
  nginx:
    depends_on:
      - web
    image: nginx:1.29
    ports:
      - '1337:80'
    volumes:
      - static_files:/home/app/web/staticfiles
      - nginx_config:/etc/nginx/conf.d
  redis:
    image: redis:latest
  web:
    env_file:
      - ./.env.prod
    expose:
      - 8000
    image: open-feed-reader:dev
    volumes:
      - db-data:/app/sqlite
      - static_files:/app/staticfiles
      - media_files:/app/mediafiles
      - nginx_config:/app/nginx
volumes:
  db-data: Null
  media_files: Null
  nginx_config: Null
  static_files: Null
