version: '3'

services:

  ofr_web:
    build:
      context: .
      ssh:
        - default
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - ofr_db
    volumes:
      # - ./app:/app:Z
      - db-media:/media
      # - ../django-user-management/src/user_management:/app/user_management:Z
      # - ../django-feed-reader-extensions/src/feeds_extensions/:/app/feeds_extensions:Z
    networks:
      - ofr_network
    environment:
      - SECRET_KEY
      - DB_DB
      - DB_PASSWORD
      - DB_USER
      - DB_HOST=ofr_db

  ofr_db:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DB}
    volumes:
      - db-data:/var/lib/postgresql/data/
    networks:
      - ofr_network


networks:
  ofr_network:
    driver: bridge

volumes:
  db-data:
  db-media: