version: '3'

services:

  ofr_web:
    image: progradedv/open-feed-reader:v0.2
    command: gunicorn --bind 0.0.0.0:8000 open_feed_reader.wsgi:application
    ports:
      - 8420:8000
    depends_on:
      - ofr_db
    volumes:
      - db-media:/media
    networks:
      - ofr_network
    environment:
      - SECRET_KEY
      - DB_DB
      - DB_PASSWORD
      - DB_USER
      - DB_HOST=ofr_db
      - ALLOWED_HOSTS
      - CSRF_TRUSTED_ORIGINS
      - DEBUG

  ofr_db:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DB}
    volumes:
      - db-data:/var/lib/postgresql/data/
    networks:
      - ofr_network


networks:
  ofr_network:
    driver: bridge

volumes:
  db-data:
  db-media:
