version: '3'

services:

  ofr_web:
    image: progradedv/open-feed-reader:v0.2.0
    command: gunicorn --bind 0.0.0.0:8000 open_feed_reader.wsgi:application
    ports:
      - 8420:8000
    depends_on:
      - ofr_db
    volumes:
      - db-media:/media
    networks:
      - ofr_network
    environment:
      - SECRET_KEY
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST=ofr_db
      - EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD
      - ALLOWED_HOSTS
      - CSRF_TRUSTED_ORIGINS
      - DEBUG

  ofr_db:
    image: postgres:15.3
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - db-data:/var/lib/postgresql/data/
    networks:
      - ofr_network


networks:
  ofr_network:
    driver: bridge

volumes:
  db-data:
  db-media:
