version: '3'

services:
  web:
    image: open-feed-reader:dev
    ports:
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      - db-data:/app/sqlite
      - static-files:/app/staticfiles
      - media-files:/app/mediafiles

volumes:
  db-data:
  static-files:
  media-files:

