version: '3'

services:

  ofr_db:
    image: postgres:17
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - db-data:/var/lib/postgresql/data/
    restart: unless-stopped
    ports:
      - 5432:5432

volumes:
  db-data:
