version: '3'

services:

  ofr_web:
    build:
      context: .
      ssh:
        - default
    ports:
      - 8000:8000
    depends_on:
      - ofr_db
    volumes:
      - db-media:/media
      - ./app:/app:Z
      - /tmp/django-logs:/var/log:Z
      - ../django-user-management/src/user_management:/app/user_management:Z
    networks:
      - ofr_network
    environment:
      - SECRET_KEY
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST=ofr_db
      - ALLOWED_HOSTS
      - DEBUG

  ofr_db:
    image: postgres:15.3
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - db-data:/var/lib/postgresql/data/
    networks:
      - ofr_network


networks:
  ofr_network:
    driver: bridge

volumes:
  db-data:
  db-media:
