version: '3'

services:
  web:
    build:
      context: .
    ports:
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      - db-data:/home/sqlite
      - static_files:/home/app/staticfiles

volumes:
  db-data:
  static_files:
