version: '3'

services:

  ofr_db:
    image: postgres:16.2
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - db-data:/var/lib/postgresql/data/
    restart: unless-stopped

volumes:
  db-data:
