[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where=["src"]

[project]
name="open_feed_reader"
version="v0.6.0"
requires-python = ">=3.13,<4.0"
dependencies = [
  "Django",
  "pillow",
  "gunicorn",
  "requests",
  "django-csp",
  "django_bleach",
  "ptpython",
  "django-extensions",
  "django-allauth",
  "feedparser",
  "beautifulsoup4",
  "redis",
]

[dependency-groups]
dev=[
  "ruff",
]

[project.scripts]
"manage.py" = "open_feed_reader.manage:main"

[tool.setuptools.package-data]
"*" = ["**/templates/**/*", "**/static/**/*"]

