# Generated by Django 5.1.6 on 2025-03-19 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed_subscriptions', '0002_entriesfolder_delete_postsfolder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SourcesFolder',
        ),
    ]
