# Generated by Django 5.1.6 on 2025-03-19 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feed_subscriptions', '0003_delete_sourcesfolder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourcesFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('sources', models.ManyToManyField(related_name='folders', to='feed_subscriptions.sourcesubcription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_folders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
