# Generated by Django 5.1.6 on 2025-03-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0021_delete_webproxy_remove_enclosure_description_and_more'),
        ('folders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcesfolder',
            name='sources',
            field=models.ManyToManyField(related_name='folders', to='feeds.source'),
        ),
    ]
