# Generated by Django 5.1.6 on 2025-07-09 01:24

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('feeds', '0001_initial'), ('feeds', '0002_auto_20190604_0845'), ('feeds', '0003_post_image_url'), ('feeds', '0004_webproxy'), ('feeds', '0005_source_description'), ('feeds', '0006_auto_20190901_1644'), ('feeds', '0007_auto_20210502_0716'), ('feeds', '0008_allow_longer_post_guid'), ('feeds', '0009_allow_source_last_change_and_last_success_to_be_blank'), ('feeds', '0010_enclosure_description_enclosure_medium'), ('feeds', '0011_source_author_source_icon_url_source_subtitle_and_more'), ('feeds', '0012_alter_entry_created_alter_source_feed_url_and_more'), ('feeds', '0013_alter_entry_options_remove_entry_index'), ('feeds', '0014_remove_source_interval_remove_source_is_cloudflare_and_more'), ('feeds', '0015_alter_source_subtitle'), ('feeds', '0016_rename_post_enclosure_entry'), ('feeds', '0017_alter_entry_created'), ('feeds', '0018_rename_due_poll_source_due_fetch_and_more'), ('feeds', '0019_remove_source_last_change_remove_source_max_index_and_more'), ('feeds', '0020_alter_source_due_fetch'), ('feeds', '0021_delete_webproxy_remove_enclosure_description_and_more')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('site_url', models.URLField(blank=True, max_length=255, null=True)),
                ('feed_url', models.URLField(max_length=512, unique=True)),
                ('image_url', models.URLField(blank=True, max_length=512, null=True)),
                ('last_feched', models.DateTimeField(blank=True, null=True)),
                ('due_fetch', models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('etag', models.CharField(blank=True, max_length=255, null=True)),
                ('last_modified', models.CharField(blank=True, max_length=255, null=True)),
                ('last_result', models.CharField(blank=True, max_length=255, null=True)),
                ('last_success', models.DateTimeField(blank=True, null=True)),
                ('live', models.BooleanField(default=True)),
                ('status_code', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('icon_url', models.URLField(blank=True, max_length=512, null=True)),
                ('subtitle', models.TextField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('min_interval', models.FloatField(default=3600)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('body', models.TextField()),
                ('link', models.CharField(blank=True, max_length=512, null=True)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('guid', models.CharField(blank=True, db_index=True, max_length=512, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.CharField(blank=True, max_length=512, null=True)),
                ('found', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='feeds.source')),
            ],
        ),
        migrations.CreateModel(
            name='Enclosure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(default=0)),
                ('href', models.CharField(max_length=512)),
                ('type', models.CharField(max_length=256)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enclosures', to='feeds.entry')),
            ],
        ),
    ]
