# Generated by Django 5.1.7 on 2025-03-19 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feeds', '0021_delete_webproxy_remove_enclosure_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedsFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('feeds', models.ManyToManyField(related_name='folders', to='feeds.source')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_folders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
